Fix setup: rewrite limpio, sin key, sin parametro, conectado a GitHub

diff --git a/PandaScript/setup b/PandaScript/setup
--- a/PandaScript/setup
+++ b/PandaScript/setup
@@ -1,5 +1,5 @@
 #!/bin/bash
-#CEPADOR Henry Chumo | 25/08/2022 | MOD PandaScript
+#CREADOR Henry Chumo | 25/08/2022 | MOD PandaScript
 #Alias : @ChumoGH
 # -*- ENCODING: UTF-8 -*-
 export PATH=$PATH:/usr/sbin:/usr/local/sbin:/usr/local/bin:/usr/bin:/sbin:/bin:/usr/games;
@@ -15,292 +15,177 @@ rm -f instala.*
 echo -e " ESPERE UN MOMENTO "
 apt-get install curl -y &>/dev/null
 apt install sudo -y &> /dev/null
-[[ -e /bin/ejecutar/msg ]] || { mkdir -p /bin/ejecutar; wget -q -O /bin/ejecutar/msg "${GITHUB_RAW}/Otros/msg"; }
-source /bin/ejecutar/msg > /dev/null
+mkdir -p /bin/ejecutar
+[[ -e /bin/ejecutar/msg ]] || wget -q -O /bin/ejecutar/msg "${GITHUB_RAW}/Otros/msg"
+source /bin/ejecutar/msg > /dev/null 2>&1
 COLS=$(tput cols)
 
-os_system(){ 
- system=$(cat -n /etc/issue |grep 1 |cut -d ' ' -f6,7,8 |sed 's/1//' |sed 's/      //') 
- distro=$(echo "$system"|awk '{print $1}') 
- case $distro in 
- Debian)vercion=$(echo $system|awk '{print $3}'|cut -d '.' -f1);; 
- Ubuntu)vercion=$(echo $system|awk '{print $2}'|cut -d '.' -f1,2);; 
- esac 
- link="https://raw.githubusercontent.com/karl1999x/PandaScript/main/Source-List/${vercion}.list" 
+os_system() {
+ system=$(cat -n /etc/issue |grep 1 |cut -d ' ' -f6,7,8 |sed 's/1//' |sed 's/      //')
+ distro=$(echo "$system"|awk '{print $1}')
+ case $distro in
+ Debian)vercion=$(echo $system|awk '{print $3}'|cut -d '.' -f1);;
+ Ubuntu)vercion=$(echo $system|awk '{print $2}'|cut -d '.' -f1,2);;
+ esac
+ link="https://raw.githubusercontent.com/karl1999x/PandaScript/main/Source-List/${vercion}.list"
 }
 
-rutaSCRIPT () {
-rm -f setup*
-act_ufw() {
-[[ -f "/usr/sbin/ufw" ]] && ufw allow 81/tcp ; ufw allow 8888/tcp
-}
-[[ -z $(cat /etc/resolv.conf | grep "8.8.8.8") ]] && echo "nameserver	8.8.8.8" >> /etc/resolv.conf
-[[ -z $(cat /etc/resolv.conf | grep "1.1.1.1") ]] && echo "nameserver	1.1.1.1" >> /etc/resolv.conf
-cd $HOME
-fun_ip () {
-MIP=$(ip addr | grep 'inet' | grep -v inet6 | grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | head -1)
-MIP2=$(wget -qO- ipv4.icanhazip.com)
-[[ "$MIP" != "$MIP2" ]] && IP="$MIP2" || IP="$MIP"
-}
-
-fun_install () {
-clear
-valid_fun
-msg -bar
-cd $HOME
-[[ -e $HOME/lista ]] && rm -f $HOME/lista*
-[[ -d ${SCPinstal} ]] && rm -rf ${SCPinstal} 
-}
-## root check
 if ! [ $(id -u) = 0 ]; then
-clear
-		echo ""
-		echo " _________________________________________________"
-		echo "	Error Fatal!!"
-		echo " _________________________________________________"
-		echo " Este script debe ejecutarse como root!"
-		echo " _________________________________________________"
-		echo " Como Solucionarlo "
-		echo " Ejecuta el script como:"
-		echo "                              (  sudo -i )"
-		echo "	                                sudo su"
-		echo "	                             Retornando . . ."
-		echo $(date)
-		exit
+    clear
+    echo ""
+    echo " _________________________________________________"
+    echo "	Error Fatal!!"
+    echo " _________________________________________________"
+    echo " Este script debe ejecutarse como root!"
+    echo " _________________________________________________"
+    echo " Como Solucionarlo "
+    echo " Ejecuta el script como:"
+    echo "                              (  sudo -i )"
+    echo "	                                sudo su"
+    echo "	                             Retornando . . ."
+    echo $(date)
+    exit 1
 fi
 
+act_ufw() {
+    [[ -f "/usr/sbin/ufw" ]] && ufw allow 81/tcp ; ufw allow 8888/tcp
+}
+
+fun_ip () {
+    MIP=$(ip addr | grep 'inet' | grep -v inet6 | grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | head -1)
+    MIP2=$(wget -qO- ipv4.icanhazip.com)
+    [[ "$MIP" != "$MIP2" ]] && IP="$MIP2" || IP="$MIP"
+}
+
 function_verify () {
-echo "verify" > $(echo -e $(echo 2f62696e2f766572696679737973|sed 's/../\\x&/g;s/$/ /'))
-echo 'MOD @ChumoGH Joaquin' > $(echo -e $(echo 2F7573722F6C69622F6C6963656E6365|sed 's/../\\x&/g;s/$/ /'))
-[[ $(dpkg --get-selections|grep -w "libpam-cracklib"|head -1) ]] || apt-get install libpam-cracklib -y &> /dev/null
-echo -e '# Modulo @ChumoGH
+    echo "verify" > $(echo -e $(echo 2f62696e2f766572696679737973|sed 's/../\\x&/g;s/$/ /'))
+    echo 'MOD @ChumoGH Joaquin' > $(echo -e $(echo 2F7573722F6C69622F6C6963656E6365|sed 's/../\\x&/g;s/$/ /'))
+    [[ $(dpkg --get-selections|grep -w "libpam-cracklib"|head -1) ]] || apt-get install libpam-cracklib -y &> /dev/null
+    echo -e '# Modulo @ChumoGH
 password [success=1 default=ignore] pam_unix.so obscure sha512
 password requisite pam_deny.so
 password required pam_permit.so' > /etc/pam.d/common-password && chmod +x /etc/pam.d/common-password
 }
 
-verificar_arq () {
-[[ ! -d ${SCPdir} ]] && mkdir ${SCPdir}
-mv -f ${SCPinstal}/$1 ${SCPdir}/$1 && chmod +x ${SCPdir}/$1
-}
-fun_ip
-
 valid_fun () {
-msg -bar
-echo -e ""
-echo -e "${cor[2]}\n\033[1;37m  Script Patrocinado por: @ChumoGH - Henry Chumo" | pv -qL 12
-echo -e ""
-msg -bar
-echo -e "  ${cor[5]} NewScriptADM Mod ChumoGH-ADM REFACTORIZADO " 
-msg -bar
-echo -e "${cor[3]}     DESENCADENANDO FICHEROS DEL SISTEMA "
-echo ""
-echo '#!/bin/bash
-# Creado por @ChumoGH
+    msg -bar
+    echo -e "${cor[2]}\n\033[1;37m  Script Patrocinado por: @ChumoGH - Henry Chumo" | pv -qL 12
+    msg -bar
+    echo -e "  ${cor[5]} NewScriptADM Mod ChumoGH-ADM REFACTORIZADO "
+    msg -bar
+    echo -e "${cor[3]}     DESENCADENANDO FICHEROS DEL SISTEMA "
+    echo '#!/bin/bash
 SCPdir="/etc/adm-lite"
 cd ${SCPdir} && ./menu' > /bin/menu && chmod +x /bin/menu
-echo '#!/bin/bash
-# Creado por @ChumoGH
+    echo '#!/bin/bash
 SCPdir="/etc/adm-lite"
 cd ${SCPdir} && ./menu' > /bin/cgh && chmod +x /bin/cgh
-echo '#!/bin/bash
-# Creado por @ChumoGH
+    echo '#!/bin/bash
 SCPdir="/etc/adm-lite"
 cd ${SCPdir} && ./menu' > /bin/adm && chmod +x /bin/adm
-msg -bar
-echo ""
-[[ -e ${SCPdir}/menu_credito ]] && ress="$(cat ${SCPdir}/menu_credito) " || ress="NULL ( no found ) "
-echo -ne "${cor[2]}\n\033[1;37m  RESELLER  : " | pv -qL 50 && sleep 1s && echo -e "\033[0;35m$ress" | pv -qL 50
-echo ""
-[[ -e ${SCPdir}/cabecalho ]] && bash ${SCPdir}/cabecalho --instalar
+    msg -bar
+    [[ -e ${SCPdir}/menu_credito ]] && ress="$(cat ${SCPdir}/menu_credito) " || ress="NULL ( no found ) "
+    echo -ne "${cor[2]}\n\033[1;37m  RESELLER  : " | pv -qL 50 && sleep 1s && echo -e "\033[0;35m$ress" | pv -qL 50
+    [[ -e ${SCPdir}/cabecalho ]] && bash ${SCPdir}/cabecalho --instalar
 }
 
 error_conex () {
-clear&&clear
-msg -bar
-echo -e "\e[3;31m   CONEXION FALLIDA  COMANDO MANUAL :  sudo apt  update" | pv -qL 50
-msg -bar3
-echo -e "\e[5m\e[1;37m\e[48;5;235m      =====>> ►►     🐼 PandaScript 🐼   ◄◄ <<=====   \e[0m"
-msg -bar3
-echo -e "\033[1;33m   EL PROBLEMA FUE UNA FALLA DE ACTUALIZACION DE SISTEMA "
-sleep 12s
-exit 1
+    clear&&clear
+    msg -bar
+    echo -e "\e[3;31m   CONEXION FALLIDA  COMANDO MANUAL :  sudo apt  update" | pv -qL 50
+    msg -bar3
+    echo -e "\e[5m\e[1;37m\e[48;5;235m      =====>> ►►     🐼 PandaScript 🐼   ◄◄ <<=====   \e[0m"
+    msg -bar3
+    echo -e "\033[1;33m   EL PROBLEMA FUE UNA FALLA DE ACTUALIZACION DE SISTEMA "
+    sleep 12s
+    exit 1
 }
 
 invalid_key () {
-msg -bar
-echo -e "\e[3;31m  La instalacion no pudo completarse correctamente" | pv -qL 50
-sleep 3
-exit 1
+    msg -bar
+    echo -e "\e[3;31m  La instalacion no pudo completarse correctamente" | pv -qL 50
+    sleep 3
+    exit 1
 }
 
 # ============================================================
 # INSTALACION SIN KEY: descarga y monta todo desde GitHub
 # ============================================================
 funkey () {
-clear&&clear
-msg -bar3
-echo -e "\e[5m\e[1;37m\e[48;5;235m      =====>> ►►  🐼 PandaScript 🐼  ◄◄ <<=====   \e[0m"
-msg -bar3
-msg -bar
-echo -e "\033[1;33m   DESCARGANDO E INSTALANDO PandaScript DESDE GITHUB ..." | pv -qL 50 || echo -e "\033[1;33m   DESCARGANDO E INSTALANDO PandaScript DESDE GITHUB ..."
-[[ ! -d ${SCPdir} ]] && mkdir -p ${SCPdir}
-[[ ! -d /etc/adm-lite/slow ]] && mkdir -p /etc/adm-lite/slow
+    clear&&clear
+    msg -bar3
+    echo -e "\e[5m\e[1;37m\e[48;5;235m      =====>> ►►  🐼 PandaScript 🐼  ◄◄ <<=====   \e[0m"
+    msg -bar3
+    msg -bar
+    echo -e "\033[1;33m   DESCARGANDO E INSTALANDO PandaScript DESDE GITHUB ..."
+    [[ ! -d ${SCPdir} ]] && mkdir -p ${SCPdir}
+    [[ ! -d /etc/adm-lite/slow ]] && mkdir -p /etc/adm-lite/slow
+    [[ ! -d /etc/ADMcgh ]] && mkdir -p /etc/ADMcgh
 
-# ---- Descargar adm-lite (panel) ----
-cd /etc
-echo " > obteniendo adm-lite.tar.gz ..."
-if wget -q -4 "${GITHUB_RAW}/adm-lite.tar.gz" -O adm-lite.tar.gz; then
-    tar -xf adm-lite.tar.gz >/dev/null 2>&1
-    chmod -R +x ${SCPdir} 2>/dev/null
-    rm -f adm-lite.tar.gz
-    echo ""
-else
-    echo "   ! FALLO al descargar adm-lite.tar.gz"
-    invalid_key
-fi
+    cd /etc
+    echo " > obteniendo adm-lite.tar.gz ..."
+    if wget -q -4 "${GITHUB_RAW}/adm-lite.tar.gz" -O adm-lite.tar.gz; then
+        tar -xf adm-lite.tar.gz >/dev/null 2>&1
+        chmod -R +x ${SCPdir} 2>/dev/null
+        rm -f adm-lite.tar.gz
+    else
+        echo "   ! FALLO al descargar adm-lite.tar.gz"
+        invalid_key
+    fi
 
-# ---- Descargar install2 y menu_inst ----
-cd ${SCPdir}
-wget -q -4 "${GITHUB_RAW}/install2" -O install2 && chmod +x install2
-wget -q -4 "${GITHUB_RAW}/menu_inst" -O menu_inst && chmod +x menu_inst
-wget -q -4 "${GITHUB_RAW}/Otros/v-new.log" -O /etc/adm-lite/local.txt 2>/dev/null
+    cd ${SCPdir}
+    wget -q -4 "${GITHUB_RAW}/install2" -O install2 && chmod +x install2
+    wget -q -4 "${GITHUB_RAW}/menu_inst" -O menu_inst && chmod +x menu_inst
+    wget -q -4 "${GITHUB_RAW}/Otros/v-new.log" -O /etc/adm-lite/local.txt 2>/dev/null
 
-# ---- msg en /bin/ejecutar ----
-mkdir -p /bin/ejecutar
-wget -q -O /bin/ejecutar/msg "${GITHUB_RAW}/Otros/ejecutar/msg" 2>/dev/null || cp -f ${SCPdir}/Otros/msg /bin/ejecutar/msg 2>/dev/null
-chmod +x /bin/ejecutar/msg 2>/dev/null
+    mkdir -p /bin/ejecutar
+    wget -q -O /bin/ejecutar/msg "${GITHUB_RAW}/Otros/ejecutar/msg" 2>/dev/null || cp -f ${SCPdir}/Otros/msg /bin/ejecutar/msg 2>/dev/null
+    chmod +x /bin/ejecutar/msg 2>/dev/null
 
-# ---- Wrappers de acceso ----
-echo '#!/bin/bash
+    echo '#!/bin/bash
 SCPdir="/etc/adm-lite"
 cd ${SCPdir} && ./menu' > /bin/menu && chmod +x /bin/menu
-echo '#!/bin/bash
+    echo '#!/bin/bash
 SCPdir="/etc/adm-lite"
 cd ${SCPdir} && ./menu' > /bin/cgh && chmod +x /bin/cgh
-echo '#!/bin/bash
+    echo '#!/bin/bash
 SCPdir="/etc/adm-lite"
 cd ${SCPdir} && ./menu' > /bin/adm && chmod +x /bin/adm
 
-# ---- Version ----
-echo "v6" > /etc/ADMcgh/v-local.log 2>/dev/null || { mkdir -p /etc/ADMcgh; echo "v6" > /etc/ADMcgh/v-local.log; }
-
-chmod -R 755 ${SCPdir}
-msg -bar
-echo -e "\033[1;32m           >> PandaScript DESCARGADO <<\033[0m"
-msg -bar
+    echo "v6" > /etc/ADMcgh/v-local.log
+    chmod -R 755 ${SCPdir}
+    msg -bar
+    echo -e "\033[1;32m           >> PandaScript DESCARGADO <<\033[0m"
+    msg -bar
 }
 
-ofus () {
-unset txtofus
-number=$(expr length $1)
-for((i=1; i<$number+1; i++)); do
-txt[$i]=$(echo "$1" | cut -b $i)
-case ${txt[$i]} in
-".")txt[$i]="x";;
-"x")txt[$i]=".";;
-"5")txt[$i]="s";;
-"s")txt[$i]="5";;
-"1")txt[$i]="@";;
-"@")txt[$i]="1";;
-"2")txt[$i]="?";;
-"?")txt[$i]="2";;
-"4")txt[$i]="0";;
-"0")txt[$i]="4";;
-"/")txt[$i]="K";;
-"K")txt[$i]="/";;
-esac
-txtofus+="${txt[$i]}"
-done
-echo "$txtofus" | rev
-}
-
-function printTitle
-{
-    echo ""
-    echo -e "\033[1;92m$1\033[1;91m"
-    printf '%0.s-' $(seq 1 ${#1})
-    echo ""
-}
-killall apt apt-get &> /dev/null
-TIME_START="$(date +%s)"
-DOWEEK="$(date +'%u')"
-[[ -e $HOME/cgh.sh ]] && rm $HOME/cgh.*
-
-fun_bar () {
-comando[0]="$1"
- (
-[[ -e $HOME/fim ]] && rm $HOME/fim
-${comando[0]} -y > /dev/null 2>&1
-touch $HOME/fim
- ) > /dev/null 2>&1 &
-echo -ne "\033[1;33m ["
-while true; do
-   for((i=0; i<18; i++)); do
-   echo -ne "\033[1;31m##"
-   sleep 0.1s
-   done
-   [[ -e $HOME/fim ]] && rm $HOME/fim && break
-   echo -e "\033[1;33m]"
-   sleep 0.5s
-   tput cuu1
-   tput dl1
-   echo -ne "\033[1;33m ["
-done
-echo -e "\033[1;33m]\033[1;31m -\033[1;32m 100%\033[1;37m"
-}
-
-function printTitle
-{
-    echo ""
-    echo -e "\033[1;92m$1\033[1;91m"
-    printf '%0.s-' $(seq 1 ${#1})
-    echo ""
-}
-msg -bar
-printTitle " ORGANIZANDO INTERFAZ DEL INSTALADOR "
-echo ""
 update_pak () {
-echo "" 
-[[ $(dpkg --get-selections|grep -w "pv"|head -1) ]] || apt install pv -y &> /dev/null 
-os_system 
-echo -e "		[ ! ]  ESPERE UN MOMENTO  [ ! ]"
-[[ $(dpkg --get-selections|grep -w "lolcat"|head -1) ]] || apt-get install lolcat -y &>/dev/null 
-[[ $(dpkg --get-selections|grep -w "figlet"|head -1) ]] || apt-get install figlet -y &>/dev/null
-echo ""
-msg -bar
-echo -e "\e[1;31m  SISTEMA:  \e[33m$distro $vercion \e[1;31m	CPU:  \e[33m$(lscpu | grep "Vendor ID" | awk '{print $3}')" 
-msg -bar
-dpkg --configure -a > /dev/null 2>&1 && echo -e "\033[94m    ${TTcent} INTENTANDO RECONFIGURAR UPDATER ${TTcent}" | pv -qL 80
-msg -bar
-echo -e "\033[94m    ${TTcent} UPDATE DATE : $(date +"%d/%m/%Y") & TIME : $(date +"%H:%M") ${TTcent}" | pv -qL 80
-[[ $(dpkg --get-selections|grep -w "net-tools"|head -1) ]] || apt-get install net-tools -y &>/dev/null
-[[ $(dpkg --get-selections|grep -w "boxes"|head -1) ]] || apt-get install boxes -y &>/dev/null
-echo ""
-apt-get install software-properties-common -y > /dev/null 2>&1 && echo -e "\033[94m    ${TTcent} INSTALANDO NUEVO PAQUETES ( S|P|C )    ${TTcent}" | pv -qL 80
-echo ""
-echo -e "\033[94m    ${TTcent} PREPARANDO BASE RAPIDA INSTALL    ${TTcent}" | pv -qL 80 
-msg -bar
-echo " "
-clear&&clear
-rm $(pwd)/$0 &> /dev/null 
-return
+    echo ""
+    [[ $(dpkg --get-selections|grep -w "pv"|head -1) ]] || apt install pv -y &> /dev/null
+    os_system
+    echo -e "		[ ! ]  ESPERE UN MOMENTO  [ ! ]"
+    [[ $(dpkg --get-selections|grep -w "lolcat"|head -1) ]] || apt-get install lolcat -y &>/dev/null
+    [[ $(dpkg --get-selections|grep -w "figlet"|head -1) ]] || apt-get install figlet -y &>/dev/null
+    echo ""
+    msg -bar
+    echo -e "\e[1;31m  SISTEMA:  \e[33m$distro $vercion \e[1;31m	CPU:  \e[33m$(lscpu | grep "Vendor ID" | awk '{print $3}')"
+    msg -bar
+    dpkg --configure -a > /dev/null 2>&1 && echo -e "\033[94m    ${TTcent} INTENTANDO RECONFIGURAR UPDATER ${TTcent}" | pv -qL 80
+    msg -bar
+    echo -e "\033[94m    ${TTcent} UPDATE DATE : $(date +"%d/%m/%Y") & TIME : $(date +"%H:%M") ${TTcent}" | pv -qL 80
+    [[ $(dpkg --get-selections|grep -w "net-tools"|head -1) ]] || apt-get install net-tools -y &>/dev/null
+    [[ $(dpkg --get-selections|grep -w "boxes"|head -1) ]] || apt-get install boxes -y &>/dev/null
+    echo ""
+    apt-get install software-properties-common -y > /dev/null 2>&1 && echo -e "\033[94m    ${TTcent} INSTALANDO NUEVO PAQUETES ( S|P|C )    ${TTcent}" | pv -qL 80
+    echo ""
+    echo -e "\033[94m    ${TTcent} PREPARANDO BASE RAPIDA INSTALL    ${TTcent}" | pv -qL 80
+    msg -bar
+    echo " "
+    clear&&clear
+    return
 }
-clear&&clear
-update_pak
-clear&&clear
-funkey
-clear&&clear
-msg -bar
-echo -e " Duracion $((($(date +%s)-$TIME_START)/60)) min."
-read -p " ENTER PARA IR AL MENU"
-#chekKEY
-[[ -e "$(which menu)" ]] && $(which menu) || echo -e " INSTALACION NO COMPLETADA CON EXITO !"
-echo " INSTALACION FINALIZADA "
-
 
 # ---------------- definiciones de msg y utilidades ----------------
-#!/bin/bash
 COLOR_VIOLETA='\033[38;5;129m'
 RESET='\033[0m'
 
@@ -371,114 +256,6 @@ msg() {
   esac
 }
 
-fun_bar () {
-comando[0]="$1"
-comando[1]="$2"
- (
-[[ -e $HOME/fim ]] && rm $HOME/fim
-${comando[0]} -y > /dev/null 2>&1
-${comando[1]} -y > /dev/null 2>&1
-touch $HOME/fim
- ) > /dev/null 2>&1 &
-echo -ne "\033[1;33m ["
-while true; do
-   for((i=0; i<18; i++)); do
-   echo -ne "\033[1;31m##"
-   sleep 0.1s
-   done
-   [[ -e $HOME/fim ]] && rm $HOME/fim && break
-   echo -e "\033[1;33m]"
-   sleep 1s
-   tput cuu1
-   tput dl1
-   echo -ne "\033[1;33m ["
-done
-echo -e "\033[1;33m]\033[1;31m -\033[1;32m 100%\033[1;37m"
-}
-
-tittle () {
-[[ -z $1 ]] && rt='adm-lite' || rt='ADMcgh'
-    clear&&clear
-    msg -bar
-    echo -e "\033[1;44;44m   \033[1;33m=====>>►► 🐲 PandaScript 🐲 ◄◄<<=====  \033[0m \033[0;33m[$(less /etc/${rt}/v-local.log)]"
-    msg -bar
-}
-in_opcion(){
-  unset opcion
-  if [[ -z $2 ]]; then
-      msg -nazu " $1: " >&2
-  else
-      msg $1 " $2: " >&2
-  fi
-  read opcion
-  echo "$opcion"
-}
-print_center(){
-  if [[ -z $2 ]]; then
-    text="$1"
-  else
-    col="$1"
-    text="$2"
-  fi
-  while read line; do
-    unset space
-    x=$(( ( 54 - ${#line}) / 2))
-    for (( i = 0; i < $x; i++ )); do
-      space+=' '
-    done
-    space+="$line"
-    if [[ -z $2 ]]; then
-      msg -azu "$space"
-    else
-      msg "$col" "$space"
-    fi
-  done <<< $(echo -e "$text")
-}
-title(){
-    clear
-    msg -bar
-    if [[ -z $2 ]]; then
-      print_center -azu "$1"
-    else
-      print_center "$1" "$2"
-    fi
-    msg -bar
- }
-enter(){
-  msg -bar
-  text="►► Presione enter para continuar ◄◄"
-  if [[ -z $1 ]]; then
-    print_center -ama "$text"
-  else
-    print_center "$1" "$text"
-  fi
-  read
- }
-back(){
-    msg -bar
-    echo -ne "$(msg -verd " [0]") $(msg -verm2 ">") " && msg -bra "\033[1;41mVOLVER"
-    msg -bar
- }
-selection_fun () {
-local selection="null"
-local range
-for((i=0; i<=$1; i++)); do range[$i]="$i "; done
-while [[ ! $(echo ${range[*]}|grep -w "$selection") ]]; do
-echo -ne "\033[1;37m ► Opcion : " >&2
-read selection
-tput cuu1 >&2 && tput dl1 >&2
-done
-echo $selection
-}
-del(){
-  for (( i = 0; i < $1; i++ )); do
-    tput cuu1 && tput dl1
-  done
-}
-
-[[ -d /bin/ejecutar ]] && {
-[[ -e /bin/ejecutar/msg ]] || wget -q -O /bin/ejecutar/msg  "${GITHUB_RAW}/Otros/msg"
-} || mkdir /bin/ejecutar
 cor[0]="\033[0m"
 cor[1]="\033[1;34m"
 cor[2]="\033[1;32m"
@@ -487,9 +264,23 @@ cor[4]="\033[1;36m"
 cor[5]="\033[1;33m"
 cor[6]="\033[1;35m"
 export -f msg
-export -f fun_bar
-export -f tittle
-export -f enter
-export -f back
-export -f print_center
-export -f in_opcion
+
+# ============================================================
+# EJECUCION PRINCIPAL
+# ============================================================
+clear&&clear
+TIME_START="$(date +%s)"
+msg -bar
+update_pak
+clear&&clear
+funkey
+clear&&clear
+msg -bar
+echo -e " Duracion $((($(date +%s)-$TIME_START)/60)) min."
+echo ""
+if [[ -e "$(which menu 2>/dev/null)" ]]; then
+    $(which menu)
+else
+    echo -e " INSTALACION NO COMPLETADA CON EXITO !"
+fi
+echo " INSTALACION FINALIZADA "
